version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper


  kafka-docker:
    image: wurstmeister/kafka
    container_name: kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181